export const queryKeys = {
  PostDetail: ["PostDetail"] as const,
  RecentPost: ["RecentPost"] as const,
  FetchComment: ["FetchComment"] as const,
  PostFavorite: ["PostFavorite"] as const,
  FavoriteStory: ["FavoriteStory"] as const,
  MyPost: ["MyPost"] as const,
  Ranking: ["Ranking"] as const,
  MyProfile: ["MyProfile"] as const,
  MyFollowers: ["MyFollowers"] as const,
  MyFollowings: ["MyFollowings"] as const,
  MyStatusMessage: ["MyStatusMessage"] as const,
  MyProfileInfo: ["MyProfileInfo"] as const,
  MyProfileImage: ["MyProfileImage"] as const,
  SearchList: ["SearchList"] as const,
} as const;
